### ISSUE TITLE
[13.0] [mass_editing] I can't debug Fields

### ISSUE THREAD

**Issue by styleo** [OCA/server-ux#191] opened 2020-08-10 10:37 UTC
Hello,

I think this is an important bug. The bug occurs for all modules but I tell you where I got it first. 

Accounting Module > Bank > statments > click on debug icon > select "view fields" I get this error.

![image](https://user-images.githubusercontent.com/67266647/89774385-106bac00-db06-11ea-83fc-aecf0b16fe3b.png)

Thanks for your help,
Emir.

**Comment by pedrobaeza** [comment] 2020-08-10 10:42
Are you able to reproduce the problem in the runbot link in the README?

**Comment by styleo** [comment] 2020-08-10 10:48
Thanks for quick reply. 
I set up two Odoo.sh projects and both of them has same problem. I don't know how to install it in runbot. I am new to Odoo so could you guide me, pls?

**Comment by pedrobaeza** [comment] 2020-08-10 10:49
Just click on the "Try me on runbot" link in the README and try there.

**Comment by styleo** [comment] 2020-08-10 10:55
The button is not functioning. :(

![image](https://user-images.githubusercontent.com/67266647/89775640-8c66f380-db08-11ea-90c4-5ad3dc9cd6ea.png)

**Comment by pedrobaeza** [comment] 2020-08-10 10:58
You are using an incorrect version: https://github.com/OCA/server-ux/tree/13.0/mass_editing

**Comment by styleo** [comment] 2020-08-10 11:03
Thanks for the correction, I will try this link. Is that mean this link : https://apps.odoo.com/apps/modules/13.0/mass_editing_v13/  (what I found in odoo app store) is incorrect version ?

**Comment by pedrobaeza** [comment] 2020-08-10 11:05
Totally. In fact, I'm going to ask for its retirement, as our company name is there incorrectly. Closing this then as the problem is that one.

**Closed as completed by pedrobaeza** 2020-08-10 11:05 UTC

**Comment by styleo** [comment] 2020-08-10 11:06
Please close it, I will check the updated version that you send me. I'm much appreciated !
