### ISSUE TITLE
[RFC] Enhancement to base_tier_validation

### ISSUE THREAD

**Issue by kittiu** [OCA/server-ux#192] opened 2020-08-11 05:33 UTC
We have the need to find a more flexible approval workflows engine. I want to try by extending this base_tier_validation first.

For example,

- [ ] Tier that auto by pass with out approval, but instead call server action - #207 
- [ ] Option to "Escalate" to 3rd person https://github.com/OCA/server-ux/pull/197
- [ ] ~~Option to Undo validation/rejection, when next step is not done~~ (not doing it)
- [ ] Persistent sub-state on document, for searching, reporting, etc. https://github.com/OCA/server-ux/pull/203
- [ ] ~~More report on approval status~~ (not doing it)
- [ ] ~~Audit trails, even if the flow is restarted~~ (not doing it)
- [ ] etc...

Sorry, it is still arbitrary ideas. But roughly, a more flexibility version of approval workflow.

I will starting doing it one by one, some as enhancement, and some as module as it deem appropriate.

cc @LoisRForgeFlow, @pedrobaeza 

---

Additional Improvements (added 14-Oct-2020)

- [ ] Replace notification system tray, with Odoo's Activity infrastrucgture.
- [ ] Revisit Base Tier Validation Helper (to group many tiers in a validation.type object for ease of management + more control)
- [ ] Auto start validation workflow, based on approving document status (i.e., Purchase Order is RFQ sent, start validation process)
- [ ] New reviewers selection option, that read HR Employee tables to get the eligible employee for validation condition (i.e., department, approval limit of each employee) 
- [ ] Tier Validation Substate enhancements, i.e., better looking UI of substate, no manual substate change, etc.
- [ ] Customised validation error messages - Business Messages rather than the system ones (explore base_exception)

**Comment by nmoturi** [comment] 2020-09-06 06:22
Hi Kitti,

other improvement list :

1. Customised validation error messages - Business Messages rather than the system ones
2. Also, can this be worked along side with base_exception OCA module..? Some of the functionality seems to be an overlap.

-Naran

**Comment by kittiu** [comment] 2020-09-06 08:32
Sure. But can you explain more. Especially on point 2.

**Comment by kittiu** [comment] 2020-10-14 04:01
@nmoturi I added the improvements in the list.

**Comment by kittiu** [comment] 2020-10-15 11:00
Among the above enhancement, I think the "Replace notification system tray, with Odoo's Activity infrastructure" is quite harsh and need more opinions.
Functionally, I think it make sense, as the tray came before activity, and once we have activity, it is more unified.

@LoisRForgeFlow do you have comment on this?

**Comment by LoisRForgeFlow** [comment] 2020-10-15 13:57
@kittiu why do you want to use activities? activities are not persistent and serve for many things, can't the tier validation get very diluted in activities systray?

Regarding the other items in the list and also continuing my answer in [this other PR](https://github.com/OCA/server-ux/pull/197#issuecomment-709140709), I think you can propose everything that are fixes or soft improvements (not important changes in data model) to base_tier_validation and start new submodules (base_tier_validation_*) for bigger improvements. Then we add a section in the settings wizard on base_tier_validation to highlight and give visibility to those improvements.

I think this is the best way to go as I am not able to follow you up on all your proposed changes as much as I would like and I apologize for that. Yet, being realistic it is the best way for you to get job done and code merged quicker.

**Comment by kittiu** [comment] 2020-10-15 14:33
@LoisRForgeFlow thank you for your comments. Please no apologize, it is me to apologize. I saw you were super busy with other projects.
I am comfortable with the splitting module and the settings wizard. :+1:

**Comment by nmoturi** [comment] 2020-10-15 23:52
@LoisRForgeFlow - The idea of using the activity groups is to avoid a single person dependent. As an example for a large volume of approvals not everything can be done by a single person, anyone with in the activity group can be approved..

Thanks,
Naran

**Comment by kittiu** [comment] 2020-10-16 01:33
@nmoturi Thank you for comment. The point that activity is not persistent is valid. The way systray works now is, it lively query on what todo for the login user, while the activity is just a created record, and so it can get diluted per say.

For your point of single person dependent. If you could explain here too in more detail.

**Closed as completed** 2021-10-19 13:34 UTC

**Comment by bunhin** [comment] 2022-12-24 06:29
@kittiu 
On a document with many states with branch flow such as a Sale Order, it is a good idea if tier_validation can provide minimal 2 steps. (step 1 _from_state _to_state and then step 2 __from_state..  _to_state...)   For example on a quotation or sales order document.  Sometimes there is a need to review the quotation before it can be sent or printed for a customer.  Once step 1 is ok the quotation can be sent to the customer and may have some changes due to negotiation etc, but once it is sent the second step then become active to prevent the modified quotation data confirmed without review.

**Comment by rvalyi** [comment] 2022-12-24 07:11
> @kittiu 
> On a document with many states with branch flow such as a Sale Order, it is a good idea if tier_validation can provide minimal 2 steps. (step 1 _from_state _to_state and then step 2 __from_state..  _to_state...)   For example on a quotation or sales order document.  Sometimes there is a need to review the quotation before it can be sent or printed for a customer.  Once step 1 is ok the quotation can be sent to the customer and may have some changes due to negotiation etc, but once it is sent the second step then become active to prevent the modified quotation data confirmed without review.    

Just in case it may help, let me mention this state machine implementation for Odoo by Acsone https://github.com/acsone/scobidoo
